---
driver:
  name: vagrant
  customize:
    memory: 1024
    cpus: 2
  network:
    - ["forwarded_port", { guest: 8080, host: 8080 }]

provisioner:
  name: chef_zero

platforms:
  - name: debian-8.2
  - name: ubuntu-12.04
  - name: ubuntu-14.04
  - name: centos-7.2
  - name: fedora-23
    run_list:
      - yum::dnf_yum_compat

suites:
  - name: default
    run_list:
      - recipe[test::prepare]
      - recipe[nomad::default]
      - recipe[test::exercise]
