---
driver:
  name: vagrant
  customize:
    memory: 1024
    cpus: 2

provisioner:
  name: chef_zero

platforms:
  - name: debian-8.2
  - name: ubuntu-12.04
  - name: ubuntu-14.04
  - name: centos-7.2

suites:
  - name: default
    run_list:
      - recipe[test::prepare]
      - recipe[nomad::default]
      - recipe[test::exercise]
